#!/bin/bash

# This script is used to build the code against a stackage snapshot.
# We use stack for this.

# This makes the script stop after the first error.
set -e

# Run stack init when stack.yaml is missing.
if [ ! -f stack.yaml ]
then
  stack init
fi

echo -e "\e[92m>> Building using resolver $1...\e[0m"
stack --resolver=$1 build
