name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        snapshot: [lts-20, lts-21, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - if: matrix.os == 'ubuntu-latest'
      run: ./build ${{ matrix.snapshot }}
    - if: matrix.os == 'windows-latest'
      run: bash build ${{ matrix.snapshot }}
