name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./build
