name: build
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  schedule:
  - cron: '0 0 * * *'
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./build
    - run: git checkout main && git merge dev
