name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        snapshot: [lts-20, lts-21, nightly]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: bash build ${{ matrix.snapshot }}
